env:
  browser: true
  node: true
  commonjs: true
  es2021: true
extends:
  - airbnb-base
  - prettier
parserOptions:
  ecmaVersion: latest
rules:
  dot-notation: 'off'
  consistent-return: 'off'
  no-param-reassign: 'off'
  no-restricted-syntax: 'off'
  no-console: 'off'
  no-await-in-loop: 'off'
